/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#504444',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'outline': '#827473',
        'outline-variant': '#d4c2c2',
        'surface-tint': '#7b5455',
        'primary': '#7b5455',
        'on-primary': '#ffffff',
        'primary-container': '#f4c2c2',
        'on-primary-container': '#734e4e',
        'inverse-primary': '#ecbaba',
        'secondary': '#5e5e5c',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1dfdc',
        'on-secondary-container': '#636360',
        'tertiary': '#8c4b55',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ffbdc5',
        'on-tertiary-container': '#84444f',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad9',
        'primary-fixed-dim': '#ecbaba',
        'on-primary-fixed': '#2f1314',
        'on-primary-fixed-variant': '#613d3e',
        'secondary-fixed': '#e4e2de',
        'secondary-fixed-dim': '#c8c6c3',
        'on-secondary-fixed': '#1b1c1a',
        'on-secondary-fixed-variant': '#474744',
        'tertiary-fixed': '#ffd9dd',
        'tertiary-fixed-dim': '#ffb2bc',
        'on-tertiary-fixed': '#3a0915',
        'on-tertiary-fixed-variant': '#70343e',
        'background': '#fcf9f8',
        'on-background': '#1c1b1b',
        'surface-variant': '#e5e2e1',
      },
      fontFamily: {
        'playfair': ['Playfair Display', 'serif'],
        'jakarta': ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'margin-desktop': '80px',
        'margin-mobile': '20px',
        'gutter': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-xl': '64px',
      },
    },
  },
  plugins: [],
}